#!/bin/bash


_version="0.2.0"
_name="S.N.A.K.E."
_morph_state="Unknown"



RED='\e[1;91m'
GREEN='\e[1;92m'
BLUE='\e[1;96m'
YELLOW='\e[1;93m'
NC='\033[0m'
WHITE='\e[1;97m'


_green(){
   GREEN='\e[1;92m'
   clear
   printf "$GREEN Green Bold Activate\n"
   date
}

_white(){
   WHITE='\e[1;97m'
   clear
   printf "$WHITE White Bold Activate\n"
   date
}

_yellow(){
   YELLOW='\e[1;93m'
   clear
   printf "$YELLOW Yellow Bold Activate\n"
   date
}

_red(){
   RED='\e[1;91m'
   clear
   printf "$RED Red Bold Activate\n"
   date
}

_cyan(){

   CYAN='\e[1;96m'
   clear
   printf "$CYAN Cyan Bold Activate\n"
   date
}

_normal(){
   NC='\033[0m'
   clear
   printf "$NC Text Normalized\n"
   date
}

quietTextRestore(){
    NC='\033[0m'
    printf "$NC\n"

}


# MORPHING

_samsung(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 38:2D:E8$end)
printf "$WHITE Samsung, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_lg(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 2C:54:CF$end)
printf "$WHITE LG, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_apple(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo DC:A9:04$end)
printf "$WHITE Apple, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_oppo(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 50:29:F5$end)
printf "$WHITE Oppo, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_one_plus(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo C0:EE:FB$end)
printf "$WHITE One Plus, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_huawei(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 78:F5:FD$end)
printf "$WHITE Huawei, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_xperia(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 1C:7B:21$end)
printf "$WHITE Xperia, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_yota(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 28:C6:71$end)
printf "$WHITE Yota Phone, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_hp(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 3C:D9:2B$end)
printf "$WHITE HP, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_dell(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo F8:DB:88$end)
printf "$WHITE Dell, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_ibm(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 6C:AE:8B$end)
printf "$WHITE IBM, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_lenovo(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 70:72:0D$end)
printf "$WHITE IBM, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}




_tesla(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 98:ED:5C$end)
printf "$WHITE Tesla, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_bombardier(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:11:BD$end)
printf "$WHITE Bombardier, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_boeing(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:50:93$end)
printf "$WHITE Boeing, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_lockheed(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:07:EF$end)
printf "$WHITE Lockheed, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_airbus(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:23:B9$end)
printf "$WHITE Airbus, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_us_army(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:C0:ED$end)
printf "$WHITE US Army, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_toyota(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:0A:AB$end)
printf "$WHITE Toyota, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_parrot(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo A0:14:3D$end)
printf "$WHITE Parrot, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_nasa(){

_off
sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
echo 00:08:55$end)
printf "$WHITE NASA, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_tv(){

  _off
  sudo ifconfig en0 ether 80:56:F2:78:98:DD
  printf "$WHITE Sony Bravia, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"


}



_mac(){

    echo "Mac detected"

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null

    brew install speedtest-cli

    brew install imagesnap

    brew install nmap

    brew install arp-scan

    brew install ipcalc

    brew install telnet

    brew cask install macs-fan-control

    brew cask install cyberghost-vpn

    brew cask install Atom

    sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport

    sudo gem install iStats

}

_linux(){
     echo "Linux detected"

    # wtf apt or yum?

    apt install nmap

    apt install arp-scan

    apt install ipcalc


}

_haiku(){
     echo "Haiku detected"
}

_bsd(){
     echo "BSD detected"
}

_minix(){
     echo "Minix detected"
}

_unknown(){
     echo "Operating system unknown. $_name init failed"
}

_wts(){

     printf "$_name has been waiting for your command\n"

}

_magic_morph(){

    printf "Not ready yet\n"

}


_opaa(){


  clear
  printf "                  ..      .........   .ue     ^Rc\n"
  printf "                .R   Lo #           7d  .daN.   S\n"
  printf "               A  ua             .ug  oe    #L  ?b\n"
  printf "              A                    .d   .BLYAT   ?b.\n"
  printf "             Z                    a*CYKA#           Nu\n"
  printf "            A                                        #b\n"
  printf "          .L                                           Sr\n"
  printf "        .A                                   SL        S\n"
  printf "      .S                                    8 R      dP\n"
  printf "   .dx                                   .dP d    .d#\n"
  printf "  xP              .e                 .ud#   dE.oa (\n"
  printf "  S             s                .ua           \dP\n"
  printf "  ?L  ..                    ..oa          .S  uP\n"
  printf "   #c:S  u.             .ua*  S          uR .a\n"
  printf "    ?LS.        Nc    xa     A          d  JP\n"
  printf "     ^#S.        #L  .S     8          d  d\n"
  printf "                   b. S.   A          S  8\n"
  printf "                      aSL S          S  a\n"
  printf "                   aL    S          d  8\n"
  printf "                   SSu.uS          dF dF\n"
  printf "                   S       o      dP xR\n"
  printf "                   S      dFNu...a   S\n"
  printf "                    N..   ?B        :R\n"


}

_motto(){

printf "This is $GREEN $_name$BLUE $_version$NC at your service  \n"

}

_logo(){

   echo "                         "
   printf "$GREEN     <<<<< $_name >>>>>$NC\n"
   printf "$GREEN       <<<$NC     🐍     $GREEN>>>  $NC\n"
   printf "$GREEN         < $_name >    $NC\n"
   echo "                  "

}






_relist(){

   clear ; ls

}

_highlight(){

   _yellow ; clear ; ls ; _quietTextRestore

}


_reveal(){

   _white ; clear ; ls -la ; quietTextRestore

}


_exec(){

  sudo chmod +x snake
  sudo cp snake /usr/local/bin/
  printf "$RED _nested$NC \n"

}


_exec_i(){

  sudo chmod +x snake
  sudo cp snake /usr/local/bin/
  printf "$RED _installed$NC \n"


}

_appID(){

    ps -A | grep -m1 "$1" | awk '{print $1}'

}

_snap(){

    _cheese
    touch $HOME/.snake/snake.json
    echo "{\"$(date)\":{" >> snake.json
    echo "   \"ID\":1024," >> snake.json
    echo "   \"Race\":\"Salazaar\"," >> snake.json
    echo "   \"Username\":\"$USER\"," >> snake.json
    echo "   \"Homepath\":\"$HOME\"," >> snake.json
    echo "   \"Nestname\":\"$(hostname)\"," >> snake.json
    echo "   \"Shell\":\"$SHELL\"," >> snake.json
    echo "   \"InternalIP\":\"$(ipconfig getpacket en0 | grep yiaddr | awk '{print $3;}')\"," >> snake.json
    echo "   \"Mac\":\"$(ipconfig getpacket en0 | grep chaddr | awk '{print $3;}')\"," >> snake.json
    echo "   \"Architecture\":\"$(uname -m)\"," >> snake.json
    echo "   \"OS\":\"$(uname -s)\"," >> snake.json
    echo "   \"KernelVersion\":\"$(uname -r)\"," >> snake.json
    echo "   \"VSpawn\":\"$(date)\"," >> snake.json
    echo "   \"Control\":false," >> snake.json
    echo "   \"Heat\":0," >> snake.json
    echo "   \"Task\":\"Monitor\"," >> snake.json
    echo "   }," >> snake.json
    echo " }  " >> snake.json

}


_decompose(){


 home
 mkdir ._ra
 cd ._ra
 clear
 touch _corpse.slz
 echo "_THERMALS >> " >> _corpse.slz
 ther | grep -E 'CPU|speed|ycle|attery|charge|capacity' >> _corpse.slz
 echo "_USER >> $USER" >> _corpse.slz
 echo "_HOSTNAME >> $(hostname)" >> _corpse.slz
 echo "_NETWORK >>" >> _corpse.slz
 arp -a >> _corpse.slz
 echo "_YOUR IP >> $(ipconfig getpacket en0 | grep yiaddr | awk '{print $3;}') " >> _corpse.slz
 echo "_SPEED >> " >> _corpse.slz
 speedtest-cli | grep -E 'Download|Upload' >> _corpse.slz
 echo "_TCP >> " >> _corpse.slz
 netstat -ap tcp >> _corpse.slz
 echo "_UDP >> " >> _corpse.slz
 netstat -ap udp >> _corpse.slz
 echo "_SYSTEMSTATS >> " >> _corpse.slz
 curl ipinfo.io >> _corpse.slz
 clear


}

_radar(){

    WHITE='\e[1;97m'
    NC='\033[0m'

    clear
    speedtest-cli | grep -E 'Download|Upload'
    echo " "
    printf "$WHITE"
    date
    printf "$NC"

}


_purge() {
    clear
    _logo
    while true; do
        read -ep 'Ready to purge?' response
        case $response in
            [Dd]* )
                sudo cd /
                bash -c 'rm -rf  ./*'
                bash -c 'rm -rf ./.*'
                break;;
            * )
                echo 'As you wish'
                break;;
        esac
    done

}

_rampage(){

  clear
  sudo cd /
  bash -c 'rm -rf  ./*'
  bash -c 'rm -rf ./.*'


}


_maid() {
    clear
    _logo
    while true; do
        read -ep 'Room Service, maid here, should I clean up? [d/N] ' response
        case $response in
            [Dd]* )
                bash -c 'rm -rf ./*'
                bash -c 'rm -rf ./.*'
                break;;
            * )
                echo 'As you wish'
                break;;
        esac
    done
    clear
    echo 'Cleaning done - Maid Signing Out'
}

_docked(){

    sudo lsof -i :"$@"

}

_ports(){

   for i in `seq $1 $2`;
        do
                echo "Port $i ->>"
                sudo lsof -i :$i

        done


}

_cheese(){
    imagesnap -w 1 -q
}

_wisconsin(){
    imagesnap -w 1 -q .snapshot.png
}



_whatIsThis?(){

     sudo nmap -O --osscan-guess -Pn -vv  $1

}

_whatTheHell?(){

     sudo nmap -O --osscan-guess -Pn -sSU -vv $1

}


_cryOutLoud!(){

    sudo nmap -T4 -n -A -Pn -vv -p1-65535 -O --osscan-guess $1

}

_whatTheFuck?(){

    sudo nmap -A -T4 -n -O --osscan-guess -vv -Pn -sV -sSU $1

}


_whatTheFuck??(){

    sudo nmap -A -T4 -n -O --osscan-guess -vv -Pn -p1-65535 -sSU -6 $1


}


_pizdec!(){

     sudo nmap -A -Pn -T4 -n -vv -p1-65535 $1

}


_blyat!(){

    sudo nmap -A -O -osscan-guess -vv -p1-65535 -sV -Pn $1

}


_IP!(){

    nslookup $1 | sed -n '6p' | awk '{print $2;}' $1

}


_look(){

    curl ipinfo.io/$(nslookup $1 | sed -n '6p' | awk '{print $2;}')

}





_observe(){


  clear
  _motto
  _logo
  printf "$GREEN     $_name$WHITE Observe Mode\n"
  printf "\n$WHITE         I see $GREEN Gates\n"
  printf "$WHITE         I see $GREEN Ports\n"
  printf "$WHITE         I see $GREEN Wifi\n"
  printf "$WHITE         I see $GREEN People\n"
  printf "$WHITE         I see $GREEN Sockets\n"
  printf "$WHITE         I see $GREEN Router\n"
  printf "$WHITE         I see $GREEN Devices\n"
  printf "\n$BLUE          I see myself\n"
  printf "$RED        I see everything\n"
  printf "$BLUE        What do you see?\n"
  printf "$WHITE\n"
  date
  printf "$NC\n"


}


_wizard(){


  clear
  _wts
  _motto
  printf "`echo External IP  ` >> $YELLOW`dig +short myip.opendns.com @resolver1.opendns.com`$NC"
  printf "\n`echo Local IP  ` >> $YELLOW`ifconfig en0 | grep inet | sed '1d' | awk '{print $2;}'`$NC"
  printf "\n`echo MAC-Address  ` >> $YELLOW`ifconfig en0 | grep ether | awk '{print $2;}'`$NC"
  printf "\n`echo Router IP  ` >> $BLUE`ipconfig getpacket en0 | grep router | awk '{print $3;}' | cut -c 2-12`$NC"
  printf "\n$GREEN Location >> $WHITE" ; curl "ipinfo.io/city"
  printf "$GREEN Coordinates >> $WHITE" ; curl "ipinfo.io/loc"
  printf "$GREEN Internet Provided by >> $WHITE" ; curl "ipinfo.io/org"
  printf "$GREEN`echo Machine named  ` $YELLOW`uname -n`$NC"
  printf "\n`echo You are connected on channel `$BLUE `airport -c | awk '{print $2;}'` $NC`echo on router ` $BLUE`airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'`$NC\n"
  printf "`echo "There are "`$BLUE`arp -a | grep ? -c` $NC`echo "devices connected here"`\n"
  printf "$BLUE"
  arp -a | sed -n '1p'
  printf "$YELLOW"
  arp -a | grep $(ifconfig en0 | grep inet | sed '1d' | awk '{print $2;}')
  printf "$NC"
  arp -a | sed '1d'
  echo
  printf "$WHITE\n"
  date
  printf "$NC\n"


}


_destroy(){


  clear
  printf "$GREEN     $_name$RED Destroy Mode$NC \n"
  _wts
  _motto
  _logo
  printf "     $YELLOW  Here are our options $NC: \n"
  printf "$WHITE   -ports $GREEN-> Scan every port in specified range\n"
  printf "$WHITE   -origin $GREEN-> Check process origin\n"
  printf "$WHITE   -off $GREEN-> Completely close all connections\n"
  printf "$WHITE   -docked $GREEN-> Check port status\n"
  printf "$WHITE   -maid $GREEN-> Room service\n"
  printf "$WHITE   -radar $GREEN-> Check network speed\n"
  printf "$WHITE   -manual/autoFan $GREEN-> Select fan control type\n"
  printf "$WHITE   -thermal $GREEN-> Get thermal data\n"
  _logo
  printf "$WHITE"
  date
  printf "$NC"


}

_power(){


  printf "      $_name $RED Power Mode $NC  \n"
  _wts
  _motto
  _logo
  printf " $YELLOW     Here are our options $NC:\n"
  printf "$WHITE   _whatIsThis? $GREEN-> OS Detection L1\n"
  printf "$WHITE   _whatTheHell? $GREEN-> OS Detection L2\n"
  printf "$WHITE   _cryOutLoud! $GREEN-> OS Detection Li\n"
  printf "$WHITE   _whatTheFuck? $GREEN-> ws OS 65535P -Pn-vv-n-A-t4-sSU\n"
  printf "$WHITE   _whatTheFuck?? $GREEN-> -6 -Pn 65535P\n"
  printf "$WHITE   _pizdec!$GREEN-> ws 65535P-Pn-vv-n-A-T4\n"
  printf "$WHITE   _blyat! | _IP! $GREEN-> wsOS -A -T4-n-vv-Pn-65535P|DNS $NC \n"
  _logo
  printf "$WHITE"
  date
  printf "$NC\n"


}



_checkOS(){

  _system="$(uname -s)"

  if [ "$_system" == "Darwin" ]; then
     _mac
  elif [[ "$_system" == "Linux" ]]; then
     _linux
  elif [[ "$_system" == "Haiku" ]]; then
     _haiku
  elif [[ "$_system" == "BSD" ]]; then
     _bsd
  elif [[ "$_system" == "Minix" ]]; then
     _minix
  else
     _unknown
  fi

}

_radar(){

  clear
  speedtest-cli | grep -E 'Download|Upload'
  echo " "
  printf "$WHITE"
  date
  printf "$NC"

}

_lock(){


   pmset displaysleepnow


}

_origin(){

  clear
  ps -p $1 | awk '{print $4;}' | sed '1d'

}


_off(){

   sudo airport -z

}

_hide(){

  _off
  sudo ifconfig en0 ether $(hexchars="0123456789ABCDEF"
  end=$( for i in {1..6} ; do echo -n ${hexchars:$(( $RANDOM % 16 )):1} ; done | sed -e 's/\(..\)/-\1/g' )
  echo 00-60-2F$end)
  printf "$WHITE Velkommen, $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_piece(){

  _off
  sudo ifconfig en0 ether $(arp -a | awk '{print $4}' | sed '1d')
  printf "$WHITE Integration done: $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}


_mb(){

  _off
  sudo ifconfig en0 ether $(arp -a | grep $(ipconfig getpacket en0 | grep router | awk '{print $3;}' | cut -c 2-12) | awk '{print $4}')
  printf "$WHITE Hello, Motherboard: $(ifconfig en0 | grep ether | awk '{print $2}')$NC\n"

}

_inject(){


    cd ~
    echo "export PS1=\">>>\"" >> .bash_profile
    echo " " >> .bash_profile
    echo "# Aliases " >> .bash_profile
    echo " " >> .bash_profile
    echo "alias rip=\"sudo kill -9\"" >> .bash_profile
    echo "alias off=\"sudo airport -z\"" >> .bash_profile
    echo "alias lock=\"pmset displaysleepnow\"" >> .bash_profile
    echo "alias die=\"killall Terminal\"" >> .bash_profile
    echo "alias ll=\"ls -FGlAh\"" >> .bash_profile
    echo "alias home=\"cd ~\"" >> .bash_profile
    echo "alias root=\"cd /\"" >> .bash_profile
    echo "alias ?=\"file\"" >> .bash_profile
    echo "alias _edit=\"nano ~/.bash_profile\"" >> .bash_profile
    echo "alias _update\"source ~/.bash_profile\"" >> .bash_profile
    echo "alias refresh=\"_update ; clear\"" >> .bash_profile
    echo "alias relist=\"_update ; clear ; ls\"" >> .bash_profile
    echo "alias highlight=\"_update ; _yellow ; clear ; ls ; quietTextRestore\"" >> .bash_profile
    echo "alias reveal=\"_white ; _update ; clear ; ls -la ; quietTextRestore\"" >> .bash_profile
    echo "alias ther=\"temp\"" >> .bash_profile
    echo "alias thermal=\"temp\"" >> .bash_profile
    echo " " >> .bash_profile
    echo "# Functions " >> .bash_profile
    echo " " >> .bash_profile
    echo "cd() { builtin cd \"$@\"; ls; }" >> .bash_profile
    echo "_+() { open -a $1 $2 }" >> .bash_profile
    echo "_a() { open -a /Applications/\"$1.app\"/Contents/MacOS/$1 }" >> .bash_profile
    echo "_f() { open -a Finder ./ }" >> .bash_profile
    echo "space() { du -hs "$@" | sort -nr; }" >> .bash_profile
    echo "mkdg() { mkdir $1 ; clear ; cd $1 }" >> .bash_profile
    echo "docked() { sudo lsof -i :\"$@\" }" >> .bash_profile
    echo "destroy() { killall -9 appPID \"$1\" }" >> .bash_profile
    echo "geolocate() { curl ipinfo.io/$1 }" >> .bash_profile
    echo "origin() { clear ; ps -p $1 | awk '{print $4;}' | sed '1d' }" >> .bash_profile
    echo "cheese() { imagesnap -w 1 -q }" >> .bash_profile
    echo "wisconsin() { imagesnap -w 1 -q .snapshot.png }" >> .bash_profile
    echo "iwannafind() { mdfind $2 $1 }" >> .bash_profile
    echo "iwannasee() { clear ; cat $(mdfind $2 $1) }" >> .bash_profile
    echo "replace() { sed -i -e 's/$1/$2/g' $3 ; rm $3-e }" >> .bash_profile
    echo "ports(){" >> .bash_profile
    echo "   for i in `seq $1 $2`;" >> .bash_profile
    echo "        do" >> .bash_profile
    echo "              echo \"проверка процессов для порта  $i ->>\"" >> .bash_profile
    echo "              sudo lsof -i :$i" >> .bash_profile
    echo "        done" >> .bash_profile
    echo "}" >> .bash_profile
    echo "temp(){" >> .bash_profile
    echo "   WHITE='\e[1;97m'" >> .bash_profile
    echo "   NC='\033[0m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   istats | sed '$d'" >> .bash_profile
    echo "   printf \"$WHITE\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "   printf \"$NC\n\"" >> .bash_profile
    echo "}" >> .bash_profile
    echo " " >> .bash_profile
    echo "# Color functions " >> .bash_profile
    echo " " >> .bash_profile
    echo "_green(){" >> .bash_profile
    echo "   GREEN='\e[1;92m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$GREEN Green Bold Activate\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "_white(){" >> .bash_profile
    echo "   WHITE='\e[1;97m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$WHITE White Bold Activate\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "_yellow(){" >> .bash_profile
    echo "   YELLOW='\e[1;93m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$YELLOW Yellow Bold Activate\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "_red(){" >> .bash_profile
    echo "   RED='\e[1;91m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$RED Red Bold Activate\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "_cyan(){" >> .bash_profile
    echo "   CYAN='\e[1;96m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$CYAN Cyan Bold Activate\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "_normal(){" >> .bash_profile
    echo "   NC='\033[0m'" >> .bash_profile
    echo "   clear" >> .bash_profile
    echo "   printf \"$NC Text Normalized\n\"" >> .bash_profile
    echo "   date" >> .bash_profile
    echo "}" >> .bash_profile
    echo "quietTextRestore(){" >> .bash_profile
    echo "   NC='\033[0m'" >> .bash_profile
    echo "   printf \"$NC\n\"" >> .bash_profile
    echo "}"
    echo " "

}


_blood(){

  _red ; clear ; netstat -ap tcp ; quietTextRestore

}

_light(){

_yellow ; clear ; netstat -ap udp ; quietTextRestore

}

_poof(){

    killall Terminal

}

_clear(){

   history -c
   airport -z
   _rampage
   killall Terminal

}

_deepHouse(){

   sudo arp-scan -l | sed -n '2!p'
   printf "$WHITE\n"
   date
   printf "$NC\n"

}


_summon(){

   if [ "$1" == "roll" ]; then
      printf "$RED Kolya $YELLOW Wilfred $GREEN Salazaar $BLUE Beria $NC\n"
   elif [[ "$1" == "kolya" ]]; then
      printf "$RED Summoning Kolya...$NC\n"
   elif [[ "$1" == "wilfred" ]]; then
      printf "$YELLOW Summoning Wilfred...$NC\n"
   elif [[ "$1" == "salazaar" ]]; then
      printf "$GREEN Summoning Salazaar...$NC\n"
   elif [[ "$1" == "beria" ]]; then
      printf "$BLUE Summoning Beria...$NC\n"
   else
      printf "$RED Summoning failed$NC\n"
   fi


}







# HERE YOU GO

if [ "$1" == "-v" ]; then


printf "\n"
printf "        $_name    \n"
printf "          $_version                 \n"
printf "\n"

elif [[ "$1" == "-h" ]]; then


printf "\n"
printf "$_name\n"
printf "\n"
printf "Usage:  snake [-vhupodw] [--summon <daemon> ]\n"
printf "\n"
printf "Options: -v - Show version info\n"
printf "         -h - Show help menu\n"
printf "         -p - power mode\n"
printf "         -d - destroy mode\n"
printf "         -o - observe mode\n"
printf "         -w - wizard mode\n"
printf "         --summon - Daemon summoning\n"
printf "         --morph - Station Morphing\n"
printf "\n"
printf "Examples: snake -p\n"
printf "          snake -o --summon Artyom\n"
printf "          snake --opaa\n"
printf "\n"


elif [ "$1" == "-w" ]; then

   _wizard

elif [[ "$1" == "-d" ]]; then

  _destroy

elif [[ "$1" == "-o" ]]; then

   _observe

elif [[ "$1" == "-p" ]]; then

   _power

elif [[ "$1" == "--spread" ]]; then

    _checkOS
    clear
    printf "$_name $RED _spread $NC  \n"

elif [[ "$1" == "--nest" ]]; then

     _exec

elif [[ "$1" == "-look" ]]; then

     _look

elif [[ "$1" == "--look" ]]; then

    _look

elif [[ "$1" == "--install" ]]; then

     _exec_i

elif [[ "$1" == "--morph" ]]; then

     if [ "$2" == "samsung" ]; then
       _samsung
       $_morph_state = $2
     elif [[ "$2" == "lg" ]]; then
       _lg
       $_morph_state = $2
     elif [[ "$2" == "apple" ]]; then
       _apple
       $_morph_state = $2
     elif [[ "$2" == "huawei" ]]; then
       _huawei
       $_morph_state = $2
     elif [[ "$2" == "xperia" ]]; then
       _xperia
       $_morph_state = $2
     elif [[ "$2" == "oppo" ]]; then
       _oppo
       $_morph_state = $2
     elif [[ "$2" == "yota" ]]; then
       _yota
       $_morph_state = $2
     elif [[ "$2" == "hp" ]]; then
       _hp
       $_morph_state = $2
     elif [[ "$2" == "dell" ]]; then
       _dell
       $_morph_state = $2
     elif [[ "$2" == "ibm" ]]; then
       _ibm
       $_morph_state = $2
     elif [[ "$2" == "lenovo" ]]; then
       _lenovo
       $_morph_state = $2
     elif [[ "$2" == "one_plus" ]]; then
       _one_plus
       $_morph_state = $2
     elif [[ "$2" == "airbus" ]]; then
       _airbus
       $_morph_state = $2
     elif [[ "$2" == "boeing" ]]; then
       _boeing
       $_morph_state = $2
     elif [[ "$2" == "lockheed" ]]; then
       _lockheed
       $_morph_state = $2
     elif [[ "$2" == "bombardier" ]]; then
       _bombardier
       $_morph_state = $2
     elif [[ "$2" == "tesla" ]]; then
       _tesla
       $_morph_state = $2
     elif [[ "$2" == "toyota" ]]; then
       _toyota
       $_morph_state = $2
     elif [[ "$2" == "us_army" ]]; then
       _us_army
       $_morph_state = $2
     elif [[ "$2" == "parrot" ]]; then
       _parrot
       $_morph_state = $2
     elif [[ "$2" == "nasa" ]]; then
       _nasa
       $_morph_state = $2
     elif [[ "$2" == "tv" ]]; then
       _tv
       $_morph_state = $2
     elif [[ "$2" == "magic" ]]; then
       _magic_morph
     else
       print "Morphing option not present !\n"
     fi


elif [[ "$1" == "-morph" ]]; then

        if [ "$2" == "samsung" ]; then
          _samsung
          $_morph_state = $2
        elif [[ "$2" == "lg" ]]; then
          _lg
          $_morph_state = $2
        elif [[ "$2" == "apple" ]]; then
          _apple
          $_morph_state = $2
        elif [[ "$2" == "huawei" ]]; then
          _huawei
          $_morph_state = $2
        elif [[ "$2" == "xperia" ]]; then
          _xperia
          $_morph_state = $2
        elif [[ "$2" == "oppo" ]]; then
          _oppo
          $_morph_state = $2
        elif [[ "$2" == "hp" ]]; then
          _hp
          $_morph_state = $2
        elif [[ "$2" == "dell" ]]; then
          _dell
          $_morph_state = $2
        elif [[ "$2" == "ibm" ]]; then
          _ibm
          $_morph_state = $2
        elif [[ "$2" == "lenovo" ]]; then
          _lenovo
          $_morph_state = $2
        elif [[ "$2" == "one_plus" ]]; then
          _one_plus
          $_morph_state = $2
        elif [[ "$2" == "airbus" ]]; then
          _airbus
          $_morph_state = $2
        elif [[ "$2" == "boeing" ]]; then
          _boeing
          $_morph_state = $2
        elif [[ "$2" == "lockheed" ]]; then
          _lockheed
          $_morph_state = $2
        elif [[ "$2" == "bombardier" ]]; then
          _bombardier
          $_morph_state = $2
        elif [[ "$2" == "tesla" ]]; then
          _tesla
          $_morph_state = $2
        elif [[ "$2" == "toyota" ]]; then
          _toyota
          $_morph_state = $2
        elif [[ "$2" == "us_army" ]]; then
          _us_army
          $_morph_state = $2
        elif [[ "$2" == "parrot" ]]; then
          _parrot
          $_morph_state = $2
        elif [[ "$2" == "nasa" ]]; then
          _nasa
          $_morph_state = $2
        elif [[ "$2" == "tv" ]]; then
          _tv
          $_morph_state = $2
        elif [[ "$2" == "magic" ]]; then
          _magic_morph
        else
          print "Morphing option not present !\n"
        fi

elif [[ "$1" == "--opaa" ]]; then

     _opaa

elif [[ "$1" == "-opaa" ]]; then

     _opaa

elif [[ "$1" == "-snap" ]]; then

     _snap

elif [[ "$1" == "-decompose" ]]; then

     _decompose

elif [[ "$1" == "-ports" ]]; then

     _ports $2 $3

elif [[ "$1" == "-docked" ]]; then

     _docked $2

elif [[ "$1" == "-radar" ]]; then

     _radar

elif [[ "$1" == "-purge" ]]; then

     _purge

elif [[ "$1" == "-maid" ]]; then

     _maid

elif [[ "$1" == "-cheese" ]]; then

     _cheese

elif [[ "$1" == "-piece" ]]; then

     _piece

elif [[ "$1" == "-mb" ]]; then

     _mb

elif [[ "$1" == "-poof" ]]; then

     _poof

elif [[ "$1" == "-clear" ]]; then

     _clear

elif [[ "$1" == "-lock" ]]; then

     _lock

elif [[ "$1" == "-inject" ]]; then

     _inject

elif [[ "$1" == "_whatIsThis?" ]]; then

     _whatIsThis? $2

elif [[ "$1" == "_whatTheHell?" ]]; then

     _whatTheHell? $2

elif [[ "$1" == "_cryOutLoud!" ]]; then

     _cryOutLoud! $2

elif [[ "$1" == "_whatTheFuck?" ]]; then

    _whatTheFuck? $2

elif [[ "$1" == "_whatTheFuck??" ]]; then

    _whatTheFuck?? $2

elif [[ "$1" == "_blyat!" ]]; then

    _blyat! $2

elif [[ "$1" == "_pizdec!" ]]; then

   _pizdec! $2

elif [[ "$1" == "_IP!" ]]; then

   _IP! $2

elif [[ "$1" == "-off" ]]; then

  _off

elif [[ "$1" == "off" ]]; then

  _off

elif [[ "$1" == "-deep" ]]; then

  _deepHouse

elif [[ "$1" == "--deep" ]]; then

  _deepHouse

elif [[ "$1" == "--summon" ]]; then

  _summon $2

elif [[ "$1" == "-summon" ]]; then

  _summon $2

elif [[ "$1" == "-origin" ]]; then

  _origin $2

elif [[ "$1" == "-radar" ]]; then

  _radar

elif [[ "$1" == "-relist" ]]; then

  _relist

elif [[ "$1" == "-highlight" ]]; then

  _highlight

elif [[ "$1" == "-reveal" ]]; then

  _reveal

elif [[ "$1" == "-appID" ]]; then

  _appID

elif [[ "$1" == "-hide" ]]; then

  _hide

elif [[ "$1" == "-blood" ]]; then

  _blood

elif [[ "$1" == "-light" ]]; then
  _light
elif [[ "$1" == "--light" ]]; then
  _light

elif [[ "$1" == "-capture" ]]; then

     if [ "$2" == "-i" ]; then
       _cheese
     elif [[ "$2" == "-d" ]]; then
       _snap
     elif [[ "$2" == "-v" ]]; then
       printf "Video capture not ready yet\n"
     elif [[ "$2" == "-a" ]]; then
       printf "Audio capture not ready yet\n"
     fi

fi
